#!/usr/bin/env python

import pygame

if __name__ == "__main__":
    pygame.init()
    pygame.joystick.init()

    done = False

    while done == False:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                done = True
            if event.type == pygame.JOYBUTTONDOWN:
                print "button pressed"
            if event.type == pygame.JOYBUTTONUP:
                print "button released"
    pygame.quit()
